export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENTS_BY_GRADE = "GET_STUDENTS_BY_GRADE";
export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const LOADING_STUDENT = "LOADING_STUDENT";
export const SEARCH_STUDENT = "SEARCH_STUDENT";
export const GET_DETAIL_STUDENT = "GET_DETAIL_STUDENT";
export const CLEAR_STUDENT = "CLEAR_STUDENT";

export const GET_TEACHERS = "GET_TEACHERS";
export const ADD_TEACHER = "ADD_TEACHER";
export const DELETE_TEACHER = "DELETE_TEACHER";
export const LOADING_TEACHER = "LOADING_TEACHER";
export const SEARCH_TEACHER = "SEARCH_TEACHER";
export const GET_DETAIL_TEACHER = "GET_DETAIL_TEACHER";

export const GET_GRADES = "GET_GRADES";
export const ADD_GRADE = "ADD_GRADE";
export const DELETE_GRADE = "DELETE_GRADE";
export const LOADING_GRADE = "LOADING_GRADE";
export const SEARCH_GRADE = "SEARCH_GRADE";
export const GET_DETAIL_GRADE = "GET_DETAIL_GRADE";

export const GET_SUBJECTS = "GET_SUBJECS";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
export const LOADING_SUBJECT = "LOADING_SUBJECT";
export const SEARCH_SUBJECT = "SEARCH_SUBJECT";
export const GET_DETAIL_SUBJECT = "GET_DETAIL_SUBJECT";

export const GET_COMPETENCIES = "GET_COMPETENCIES";
export const ADD_COMPETENCY = "ADD_COMPETENCY";
export const DELETE_COMPETENCY = "DELETE_COMPETENCY";
export const LOADING_COMPETENCY = "LOADING_COMPETENCY";
export const SEARCH_COMPETENCY = "SEARCH_COMPETENCY";
export const GET_DETAIL_COMPETENCY = "GET_DETAIL_COMPETENCY";

export const GET_SCORES = "GET_SCORES";
export const GET_SCORES_BY_GRADE = "GET_SCORES_BY_GRADE";
export const ADD_SCORE = "ADD_SCORE";
export const DELETE_SCORE = "DELETE_SCORE";
export const LOADING_SCORE = "LOADING_SCORE";
export const SEARCH_SCORE = "SEARCH_SCORE";
export const GET_DETAIL_SCORE = "GET_DETAIL_SCORE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_DEPARTEMENT = "GET_DEPARTEMENT";
export const ADD_DEPARTEMENT = "ADD_DEPARTEMENT";
export const DELETE_DEPARTEMENT = "DELETE_DEPARTEMENT";
export const LOADING_DEPARTEMENT = "LOADING_DEPARTEMENT";
export const GET_DETAIL_DEPARTEMENT = "GET_DETAIL_DEPARTEMENT";
